site_name: Geolonia Handbook

copyright: Copyright &copy; 2014 Geiolonia Inc.

theme:
  name: material
  language: ja
  custom_dir: theme/overrides
  palette:
    primary: white
  features:
    - search.suggest
plugins:
  - offline
  - search
extra_css:
  - assets/style.css
